# Generated by Django 5.2.1 on 2025-05-13 02:32

import django.db.models.deletion
import senjor.core.schema
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', senjor.core.schema.GQLTextField()),
                ('receiver', senjor.core.schema.GQLForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', senjor.core.schema.GQLForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', senjor.core.schema.GQLCharField(max_length=100)),
                ('messages', senjor.core.schema.GQLManyToManyField(to='chat.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
